### ISSUE TITLE
load h5py error

### ISSUE THREAD

**Issue by ZhaoJinHA** [twtygqyy/pytorch-vdsr#11]
Thank you for your code! When I run test.py, it works well. However, when I use pretrained model, it raises the following errors:  (I use pytorch in Windows, I don't known if this will affect something)

python main.py --cuda --pretrained model/model_epoch_50.pth
Namespace(batchSize=128, clip=0.4, cuda=True, lr=0.1, momentum=0.9, nEpochs=50, pretrained='model/model_epoch_50.pth', resume='', start_epoch=1, step=10, threads=1, weight_decay=0.0001)
Random Seed:  9559
===> Loading datasets
===> Building model
===> Setting GPU
=> loading model 'model/model_epoch_50.pth'
Y:\Software\Anaconda3\lib\site-packages\torch\serialization.py:286: SourceChangeWarning: source code of class 'torch.nn.parallel.data_parallel.DataParallel' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Y:\Software\Anaconda3\lib\site-packages\torch\serialization.py:286: SourceChangeWarning: source code of class 'vdsr.Net' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Y:\Software\Anaconda3\lib\site-packages\torch\serialization.py:286: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Y:\Software\Anaconda3\lib\site-packages\torch\serialization.py:286: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Y:\Software\Anaconda3\lib\site-packages\torch\serialization.py:286: SourceChangeWarning: source code of class 'torch.nn.modules.activation.ReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
===> Setting Optimizer
===> Training
Epoch=1, lr=0.1
Traceback (most recent call last):
  File "main.py", line 128, in <module>
    main()
  File "main.py", line 83, in main
    train(training_data_loader, optimizer, model, criterion, epoch)
  File "main.py", line 101, in train
    for iteration, batch in enumerate(training_data_loader, 1):
  File "Y:\Software\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 301, in __iter__
    return DataLoaderIter(self)
  File "Y:\Software\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 158, in __init__
    w.start()
  File "Y:\Software\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "Y:\Software\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "Y:\Software\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "Y:\Software\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "Y:\Software\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle h5py.h5d.DatasetID objects

Y:\Pytorch_project\from_github\VDSR>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "Y:\Software\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "Y:\Software\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by twtygqyy** [comment]
@ZhaoJinHA I haven't tried the script on windows, but it should work on linux,
check your data and can change model = torch.nn.DataParallel(model).cuda()  to  model = model.cuda(), see if it works

**Comment by ZhaoJinHA** [comment]
@twtygqyy Thank you for your advice. I did what you sayed, but still get error. I think this error is mainly related to data loading part, because test.py can work well. Now I only run main.py without pretrained, the error raises like follow. Maybe it's result from the difference between Window and Linux. Or I made other mistakes? How do you think of this?

Y:\Pytorch_project\from_github\VDSR>python main.py --cuda
Namespace(batchSize=128, clip=0.4, cuda=True, lr=0.1, momentum=0.9, nEpochs=50, pretrained='', resume='', start_epoch=1, step=10, threads=1, weight_decay=0.0001)
Random Seed:  5261
===> Loading datasets
===> Building model
===> Setting GPU
===> Setting Optimizer
===> Training
Epoch=1, lr=0.1
Traceback (most recent call last):
  File "main.py", line 135, in <module>
    main()
  File "main.py", line 88, in main
    train(training_data_loader, optimizer, model, criterion, epoch)
  File "main.py", line 108, in train
    for iteration, batch in enumerate(training_data_loader, 1):
  File "Y:\Software\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 301, in __iter__
    return DataLoaderIter(self)
  File "Y:\Software\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 158, in __init__
    w.start()
  File "Y:\Software\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "Y:\Software\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "Y:\Software\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "Y:\Software\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "Y:\Software\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle h5py.h5d.DatasetID objects

Y:\Pytorch_project\from_github\VDSR>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "Y:\Software\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "Y:\Software\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by ZhaoJinHA** [comment]
@twtygqyy Finally, I find the solution is very simple: just change "training_data_loader = DataLoader(dataset=train_set, num_workers=opt.threads , batch_size=opt.batchSize, shuffle=True)" to
"training_data_loader = DataLoader(dataset=train_set, batch_size=opt.batchSize, shuffle=True)". After this change, it can work on windows. Thank you again for your code : )

**Comment by twtygqyy** [comment]
@ZhaoJinHA Good to hear that you solved the issue!
