### ISSUE TITLE
training issue when read h5 file

### ISSUE THREAD

**Issue by leixiang90** [twtygqyy/pytorch-vdsr#3]
xl@xl-All-Series:~/work/pytorch-vdsr-master$ python main.py 
Namespace(batchSize=64, clip=0.4, cuda=False, lr=0.001, momentum=0.9, nEpochs=50, pretrained='', resume='', start_epoch=1, step=10, threads=4, weight_decay=0.0001)
('Random Seed: ', 8148)
===> Loading datasets
===> Building model
===> Setting GPU
===> Setting Optimizer
===> Training
Epoch=1, lr=0.001
===> Epoch[1](100/209): Loss: 222.2530212402
===> Epoch[1](200/209): Loss: 226.6688232422
Checkpoint saved to model/model_epoch_1.pth
Epoch=2, lr=0.001
Traceback (most recent call last):
  File "main.py", line 126, in <module>
    main()
  File "main.py", line 81, in main
    train(training_data_loader, optimizer, model, criterion, epoch)
  File "main.py", line 99, in train
    for iteration, batch in enumerate(training_data_loader, 1):
  File "/home/xl/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 198, in __next__
    return self._process_next_batch(batch)
  File "/home/xl/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 239, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/home/xl/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 41, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xl/work/pytorch-vdsr-master/dataset.py", line 13, in __getitem__
    return torch.from_numpy(self.data[index,:,:,:]).float(), torch.from_numpy(self.target[index,:,:,:]).float()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2804)
  File "/home/xl/anaconda2/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 494, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2804)
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/h5d.c:3413)
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_proxy.c:2008)
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_proxy.c:1656)
IOError: Can't read data (Wrong b-tree signature)

do you come across this error?

**Comment by twtygqyy** [comment]
@leixiang90 can you have a try with threads = 1?

**Comment by leixiang90** [comment]
@twtygqyy It works! thanks.

can you provide a parameter settings for train this network, like lr, epoch nums, step or weight initialization？ I use the default settings. The loss does not seems to converge. Thanks!

**Comment by twtygqyy** [comment]
@leixiang90 How many epochs have you trained? The loss should be able to converge gradually with the defaulting parameters.

**Comment by ZhangDY827** [comment]
@leixiang90  Hi , I met the same problem 
Namespace(batchSize=64, cuda=True, lr=0.0001, momentum=0.9, nEpochs=100, pretrained='', resume='', start_epoch=1, step=100, threads=1, weight_decay=0.0001)
True
('Random Seed: ', 6940)
===> Loading datasets
(11712, 1, 32, 32)
===> Building model
===> Setting GPU
===> Setting Optimizer
===> Training
epoch = 1 lr = 0.0001
Traceback (most recent call last):
  File "main.py", line 141, in <module>
    main()
  File "main.py", line 85, in main
    train(training_data_loader, optimizer, model, criterion, epoch)
  File "main.py", line 103, in train
    for iteration, batch in enumerate(training_data_loader, 1):
  File "/home/zhangdongyang/tensorflow/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 174, in __next__
    return self._process_next_batch(batch)
  File "/home/zhangdongyang/tensorflow/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 198, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/home/zhangdongyang/tensorflow/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 34, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zhangdongyang/pytorch-LapSRN-master/dataset.py", line 15, in __getitem__
    print(self.data[index,:,:,:].shape)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zhangdongyang/tensorflow/local/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 496, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
IOError: Can't read data (wrong B-tree signature)

I generated the train data using https://github.com/twtygqyy/pytorch-LapSRN/tree/master/data. But the error disappear when use the provided lap_pry_x4_small.h5. How did you solve the problem. Thanks a lot.

**Comment by hythbr** [comment]
@twtygqyy  thank your work!
I trained the VDSR model  on 91 images augmented by provided generate_train.m.  I use the default settings. but, the loss does not seems to converge after 50 epochs.  Could you give me some advice? Thanks!

**Comment by twtygqyy** [comment]
Please refer #6, actually PNSR will not increase after 50 epochs will default settings and you can consider the training is done.
