### ISSUE TITLE
Error when loading data generated from the 'generate_train.m' code

### ISSUE THREAD

**Issue by boyurmit** [twtygqyy/pytorch-vdsr#8]
Hi,

I'm using the code 'generate_train.m' in the data folder to generate '.h5' file for the 91-Image dataset. All the settings are the default in the .m file. However, when I load the generated .h5 dataset, python report the follows error:

Traceback (most recent call last):
  File "/home/boyu/DL/SR/pytorch-vdsr-master/main.py", line 128, in <module>
    main()
  File "/home/boyu/DL/SR/pytorch-vdsr-master/main.py", line 82, in main
    train(training_data_loader, optimizer, model, criterion, epoch)
  File "/home/boyu/DL/SR/pytorch-vdsr-master/main.py", line 101, in train
    for iteration, batch in enumerate(training_data_loader, 1):
  File "/home/boyu/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 187, in __next__
    return self._process_next_batch(batch)
  File "/home/boyu/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/home/boyu/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/boyu/DL/SR/pytorch-vdsr-master/dataset.py", line 13, in __getitem__
    return torch.from_numpy(self.data[index,:,:,:]).float(), torch.from_numpy(self.target[index,:,:,:]).float()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/boyu/.local/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 496, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
IOError: Can't read data (wrong B-tree signature)

I'm using Matlab 2017b, pytorch 0.2.0.post3 and h5py 2.7.1. 
Does anyone meet the same problem? Thank you!

**Comment by twtygqyy** [comment]
@boyurmit Please try to set --threads 1 as an option.

**Comment by boyurmit** [comment]
@twtygqyy It works. Thanks!

**Comment by cvguet** [comment]
It works. Thanks!
